version: "2.4"
services:
  mongo: 
    image: mongo:6
    restart: always
    ports:
      - 27033:27017
    volumes:
      - ./volumes/mongo:/data/db

  cloud-backend:
    build: 
      context: cloud-backend
    container_name: cloud-backend
    environment: 
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
    ports:
      - 3001:3001
    depends_on:
      - mongo
    volumes:
      - ./volumes/uploads:/usr/app/uploads
  
  cloud-frontend:
    build: 
      context: cloud-frontend
      args:
        VITE_BASE_URL: ${VITE_BASE_URL}
    container_name: cloud-frontend
    restart: "always"
    environment: 
      VITE_BASE_URL: ${VITE_BASE_URL}
    ports:
      - "80:80"